language: python

install:
 - pip install -r requirements.txt
 - pip3 install black
 - pip3 install flake8
 - pip3 install coverage
 - pip3 install coveralls

script:
 - black .
 - flake8 --max-line-length=100

after_script:
  - coveralls